### ISSUE TITLE
change zoom on product page like this sample:

### ISSUE THREAD

**Issue by mehrdad2** [hitechSense/carpet-project#6]
https://www.feizy.com/ATARAH-6571F-BLUE-MULTI-3586571FBLUMLT/

**## user can zoom in more**

**Comment by shimafaraji** [comment]
Done

(For the image gallery zoom feature to work, the images you upload must be larger than the gallery size you select for this option.)
http://carpet.rivalrydemo.com/product/hand-painted-ceramic-urn-copy/
